version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing..."
  build:
    commands:
      - echo "Build started"
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
