version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Validating code..."
      - python -m py_compile application.py
      - python -c "from application import application"
      - echo "Build passed!"
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
